#!/bin/bash
#
# Security Setup Script
# Configures UFW firewall, fail2ban, and SSL certificates
#
# Usage: sudo bash scripts/install/06-security-setup.sh
#

set -euo pipefail

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() {
    echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')] ✅ $1${NC}"
}

log_warning() {
    echo -e "${YELLOW}[$(date +'%Y-%m-%d %H:%M:%S')] ⚠️  $1${NC}"
}

log "Setting up security..."

# Install UFW
log "Installing UFW firewall..."
apt install -y ufw

# Configure UFW rules
log "Configuring UFW rules..."
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp comment 'SSH'
ufw allow 443/tcp comment 'HTTPS'
ufw allow 8443/tcp comment 'code-server'

# Enable UFW
log "Enabling UFW..."
ufw --force enable

# Install fail2ban
log "Installing fail2ban..."
apt install -y fail2ban

# Create fail2ban config for code-server
log "Creating fail2ban configuration for code-server..."
mkdir -p /etc/fail2ban/filter.d
cat > /etc/fail2ban/filter.d/code-server.conf << 'EOF'
[Definition]
failregex = ^.*Failed login attempt.*from <HOST>.*$
            ^.*Invalid password.*from <HOST>.*$
ignoreregex =
EOF

# Create fail2ban jail for code-server
mkdir -p /etc/fail2ban/jail.d
cat > /etc/fail2ban/jail.d/code-server.conf << 'EOF'
[code-server]
enabled = true
port = 8443
filter = code-server
logpath = /var/log/code-server/*.log
maxretry = 5
bantime = 3600
findtime = 600
EOF

# Create log directory for code-server (fail2ban needs it)
mkdir -p /var/log/code-server
chmod 755 /var/log/code-server

# Enable and start fail2ban
log "Starting fail2ban..."
systemctl enable fail2ban
systemctl restart fail2ban

# Note: SSL certificates are generated automatically by code-server
log_success "Security setup completed!"
log ""
log "Security configuration:"
log "  ✅ UFW firewall enabled"
log "     - Port 22 (SSH): ALLOWED"
log "     - Port 443 (HTTPS): ALLOWED"
log "     - Port 8443 (code-server): ALLOWED"
log "     - All other ports: DENIED"
log ""
log "  ✅ fail2ban configured"
log "     - Protecting code-server (port 8443)"
log "     - Max retries: 5"
log "     - Ban time: 1 hour"
log ""
log "  ✅ SSL/TLS"
log "     - Self-signed certificate (generated by code-server)"
log ""
log "To check firewall status:"
log "  sudo ufw status verbose"
log ""
log "To check fail2ban status:"
log "  sudo fail2ban-client status"
log "  sudo fail2ban-client status code-server"
log ""
log_warning "Note: Browser will show security warning for self-signed certificate."
log "For production, consider setting up Let's Encrypt:"
log "  sudo apt install certbot"
log "  sudo certbot certonly --standalone -d yourdomain.com"
