#!/bin/bash
#
# 2FA Setup for code-server using OAuth2 Proxy
# Provides Google OAuth authentication with optional TOTP 2FA
#
# Usage: sudo bash scripts/install/08-2fa-setup.sh
#

set -euo pipefail

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() { echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1"; }
log_success() { echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')] ✅ $1${NC}"; }
log_error() { echo -e "${RED}[$(date +'%Y-%m-%d %H:%M:%S')] ❌ $1${NC}"; }
log_warn() { echo -e "${YELLOW}[$(date +'%Y-%m-%d %H:%M:%S')] ⚠️  $1${NC}"; }

# ============================================================
# Configuration - MUST BE SET BEFORE RUNNING
# ============================================================
DOMAIN="${DOMAIN:-code.example.com}"
OAUTH_PROVIDER="${OAUTH_PROVIDER:-google}"  # google, github, or gitlab
OAUTH_CLIENT_ID="${OAUTH_CLIENT_ID:-}"
OAUTH_CLIENT_SECRET="${OAUTH_CLIENT_SECRET:-}"
ALLOWED_EMAILS="${ALLOWED_EMAILS:-}"  # Comma-separated list of allowed emails
COOKIE_SECRET=$(openssl rand -base64 32 | tr -d '\n')

# ============================================================
# Validation
# ============================================================
log "Validating configuration..."

if [ -z "$OAUTH_CLIENT_ID" ] || [ -z "$OAUTH_CLIENT_SECRET" ]; then
    log_error "OAuth credentials not configured!"
    echo ""
    echo "Please set the following environment variables before running:"
    echo "  export DOMAIN=code.yourdomain.com"
    echo "  export OAUTH_CLIENT_ID=your-client-id"
    echo "  export OAUTH_CLIENT_SECRET=your-client-secret"
    echo "  export ALLOWED_EMAILS=you@example.com,colleague@example.com"
    echo ""
    echo "To get OAuth credentials:"
    echo "  Google: https://console.cloud.google.com/apis/credentials"
    echo "  GitHub: https://github.com/settings/developers"
    echo "  GitLab: https://gitlab.com/-/profile/applications"
    exit 1
fi

log_success "Configuration validated"

# ============================================================
# Install OAuth2 Proxy
# ============================================================
log "Installing OAuth2 Proxy..."

OAUTH2_PROXY_VERSION="7.6.0"
OAUTH2_PROXY_URL="https://github.com/oauth2-proxy/oauth2-proxy/releases/download/v${OAUTH2_PROXY_VERSION}/oauth2-proxy-v${OAUTH2_PROXY_VERSION}.linux-amd64.tar.gz"

cd /tmp
wget -q "$OAUTH2_PROXY_URL" -O oauth2-proxy.tar.gz
tar -xzf oauth2-proxy.tar.gz
mv oauth2-proxy-v${OAUTH2_PROXY_VERSION}.linux-amd64/oauth2-proxy /usr/local/bin/
chmod +x /usr/local/bin/oauth2-proxy
rm -rf oauth2-proxy*

log_success "OAuth2 Proxy installed"

# ============================================================
# Create OAuth2 Proxy configuration
# ============================================================
log "Creating OAuth2 Proxy configuration..."

mkdir -p /etc/oauth2-proxy

cat > /etc/oauth2-proxy/oauth2-proxy.cfg << EOF
# OAuth2 Proxy Configuration for code-server
# Generated by 2fa-setup.sh

# HTTP Configuration
http_address = "127.0.0.1:4180"
https_address = ""

# Upstream (code-server)
upstreams = ["http://127.0.0.1:8080"]

# Cookie settings
cookie_name = "_oauth2_proxy"
cookie_secret = "${COOKIE_SECRET}"
cookie_secure = true
cookie_httponly = true
cookie_samesite = "lax"
cookie_expire = "168h"  # 7 days
cookie_refresh = "1h"

# Provider configuration
provider = "${OAUTH_PROVIDER}"
client_id = "${OAUTH_CLIENT_ID}"
client_secret = "${OAUTH_CLIENT_SECRET}"
redirect_url = "https://${DOMAIN}/oauth2/callback"

# Email validation
email_domains = ["*"]
$(if [ -n "$ALLOWED_EMAILS" ]; then echo "authenticated_emails_file = \"/etc/oauth2-proxy/authenticated_emails.txt\""; fi)

# Session settings
session_store_type = "cookie"

# Logging
standard_logging = true
auth_logging = true
request_logging = true

# Reverse proxy mode
reverse_proxy = true
real_client_ip_header = "X-Forwarded-For"
set_xauthrequest = true
pass_access_token = false
pass_authorization_header = false

# Skip auth for health checks
skip_auth_routes = [
    "^/healthz$",
    "^/ping$"
]

# Custom error pages
custom_sign_in_logo = ""
banner = "Virtual Desktop Server - ${DOMAIN}"
footer = "Secured by OAuth2 Proxy"
EOF

# Create allowed emails file if specified
if [ -n "$ALLOWED_EMAILS" ]; then
    echo "$ALLOWED_EMAILS" | tr ',' '\n' > /etc/oauth2-proxy/authenticated_emails.txt
    chmod 600 /etc/oauth2-proxy/authenticated_emails.txt
    log_success "Created allowed emails list"
fi

chmod 600 /etc/oauth2-proxy/oauth2-proxy.cfg

log_success "OAuth2 Proxy configuration created"

# ============================================================
# Create systemd service
# ============================================================
log "Creating systemd service..."

cat > /etc/systemd/system/oauth2-proxy.service << 'EOF'
[Unit]
Description=OAuth2 Proxy for code-server authentication
Documentation=https://oauth2-proxy.github.io/oauth2-proxy/
After=network.target code-server.service
Wants=code-server.service

[Service]
Type=simple
User=oauth2proxy
Group=oauth2proxy
ExecStart=/usr/local/bin/oauth2-proxy --config=/etc/oauth2-proxy/oauth2-proxy.cfg
Restart=always
RestartSec=5

# Security hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/log

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=oauth2-proxy

[Install]
WantedBy=multi-user.target
EOF

# Create service user
if ! id "oauth2proxy" &>/dev/null; then
    useradd -r -s /bin/false oauth2proxy
fi

log_success "Systemd service created"

# ============================================================
# Update Nginx configuration
# ============================================================
log "Updating Nginx configuration for OAuth2 Proxy..."

cat > /etc/nginx/sites-available/code-server-oauth << EOF
# Nginx configuration for code-server with OAuth2 Proxy
# Generated by 2fa-setup.sh

upstream oauth2_proxy {
    server 127.0.0.1:4180;
}

upstream code_server {
    server 127.0.0.1:8080;
}

server {
    listen 80;
    server_name ${DOMAIN};
    return 301 https://\$server_name\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${DOMAIN};

    # SSL Configuration
    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # OAuth2 Proxy endpoints
    location /oauth2/ {
        proxy_pass http://oauth2_proxy;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Scheme \$scheme;
        proxy_set_header X-Auth-Request-Redirect \$request_uri;
    }

    location = /oauth2/auth {
        proxy_pass http://oauth2_proxy;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Scheme \$scheme;
        proxy_set_header Content-Length "";
        proxy_pass_request_body off;
    }

    # Protected code-server location
    location / {
        auth_request /oauth2/auth;
        error_page 401 = /oauth2/sign_in;

        # Pass auth info to code-server
        auth_request_set \$user \$upstream_http_x_auth_request_user;
        auth_request_set \$email \$upstream_http_x_auth_request_email;
        proxy_set_header X-User \$user;
        proxy_set_header X-Email \$email;

        # WebSocket support
        proxy_pass http://code_server;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # Timeout settings for long connections
        proxy_connect_timeout 60s;
        proxy_send_timeout 600s;
        proxy_read_timeout 600s;

        # Buffering settings
        proxy_buffering off;
        proxy_request_buffering off;
    }

    # Health check endpoint (no auth required)
    location /healthz {
        return 200 "OK";
        add_header Content-Type text/plain;
    }
}
EOF

log_success "Nginx configuration created"

# ============================================================
# Enable services
# ============================================================
log "Enabling services..."

systemctl daemon-reload
systemctl enable oauth2-proxy

# Don't start yet - user needs to configure SSL first
log_warn "OAuth2 Proxy installed but NOT started"

# ============================================================
# Summary
# ============================================================
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║          🔐 2FA Setup Complete (OAuth2 Proxy)                 ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║                                                               ║"
echo "║  Configuration:                                               ║"
echo "║    Domain: ${DOMAIN}"
echo "║    Provider: ${OAUTH_PROVIDER}"
echo "║    Proxy: http://127.0.0.1:4180                              ║"
echo "║                                                               ║"
echo "║  Next Steps:                                                  ║"
echo "║                                                               ║"
echo "║  1. Get SSL certificate:                                      ║"
echo "║     certbot certonly --nginx -d ${DOMAIN}"
echo "║                                                               ║"
echo "║  2. Enable Nginx config:                                      ║"
echo "║     ln -sf /etc/nginx/sites-available/code-server-oauth \\    ║"
echo "║            /etc/nginx/sites-enabled/code-server              ║"
echo "║     nginx -t && systemctl reload nginx                       ║"
echo "║                                                               ║"
echo "║  3. Update code-server to listen on 127.0.0.1:8080:          ║"
echo "║     Edit ~/.config/code-server/config.yaml                   ║"
echo "║                                                               ║"
echo "║  4. Start OAuth2 Proxy:                                       ║"
echo "║     systemctl start oauth2-proxy                             ║"
echo "║                                                               ║"
echo "╚══════════════════════════════════════════════════════════════╝"
